version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bekarys7
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  user-service:
    build: 
      context: .
      dockerfile: user-service/Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:bekarys7@postgres:5432/postgres?sslmode=disable
      - NATS_URL=nats://nats:4222
    ports:
      - "50051:50051"
    depends_on:
      - postgres
      - nats

  product-service:
    build: 
      context: .
      dockerfile: product-service/Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:bekarys7@postgres:5432/postgres?sslmode=disable
      - REDIS_ADDR=redis:6379
      - NATS_URL=nats://nats:4222
    ports:
      - "50052:50052"
    depends_on:
      - postgres
      - redis
      - nats

  order-service:
    build: 
      context: .
      dockerfile: order-service/Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:bekarys7@postgres:5432/postgres?sslmode=disable
      - NATS_URL=nats://nats:4222
    ports:
      - "50053:50053"
    depends_on:
      - postgres
      - nats

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    environment:
      - USER_SERVICE_URL=user-service:50051
      - PRODUCT_SERVICE_URL=product-service:50052
      - ORDER_SERVICE_URL=order-service:50053
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
      - order-service

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - api-gateway

volumes:
  pgdata:
